version: '3.3'

networks: 
    frontend:
    backend:

volumes: 
    postgres:
    redis:

services: 
    # nginx:
    #     container_name: nginx
    #     ports: 
    #         - 80:80
    #         - 443:443
    #     networks: 
    #         - backend
    #         - frontend
    bot:
        container_name: bot
        build: .
        ports: 
            - 5000:5000
        networks: 
            - backend
    
    # postgres:
    #     container_name: postgres
    #     image: postgres
    #     networks: 
    #         - backend
    
    redis:
        container_name: redis
        image: redis:6.0-rc2-alpine
        volumes: 
            - redis:/data
        networks: 
            - backend
    
    # celery:
    #     container_name: celery
    #     image: celery
    #     networks: 
    #         - backend